development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://xnozsnipvlqzru:c85ddfe3d869cafbc5f42dc165f9b2f12189a7765864a060c9021ce7b3170367@ec2-54-243-239-66.compute-1.amazonaws.com:5432/d2mmd79ahkr1oe
  channel_prefix: webapp_production
